### ISSUE TITLE
Unable to get data into Dynamo DB

### ISSUE THREAD

**Issue by sourav-bhattacharya** [awslabs/serverless-chatbots-workshop#3]
Bonjour Olivier!

First off, thanks for such an exhaustive guide on building a chatbot. It's amazing that you've put in so much effort to create an amazing document.

I am a relatively new to Cloud, AWS & ChatBots, so I may have done something wrong. But as far as I can see, I followed your instructions to the letter.

Sadly, I can't see any data in the Dynamo DB when I type into the messaging window for the FB page/app that I've created.

Please let me know how I can help you troubleshoot this issue.

Hoping you'll help a newbie get the hang of the whole Cloud, AWS & Chatbot realm.

Thanks for reading!
Regards.
Sourav Bhattacharya

**Comment by jarrettj** [comment]
Hey,

Yip, I feel your pain. This walkthrough is broken at most steps.

I think it being 5 months out of date is why it does not work. 

JJ

**Comment by willgarcia** [comment]
@jarrettj It worked for me after fixing a misconfiguration on my webhooks. 

@sourav9385 I would recommend that you start debugging on slack (with the`/helloworld` command) / facebook (use test button on webhook's subscription) to see if at least one these services is working. 

Having a look to the API Cloudwatch logs / Lambda F. logs also helped me to understand the source of the problem.

**Comment by jarrettj** [comment]
Thanks @willgarcia for the advice :)
