### ISSUE TITLE
Elastricsearch access policy gives creates elasticserch domain error

### ISSUE THREAD

**Issue by suruchikaursihra** [awslabs/serverless-chatbots-workshop#6]
while submitting the access policy it gives an error 

CreateElasticsearchDomain: {"message":"Error setting policy: [{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"es:ESHttpGet\",\"es:ESHttpHead\"],\"Resource\":\"arn:aws:es:<ap-south-1>:<220876168477>:domain/chatbot/*\"},{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":\"es:ESHttpP*\",\"Resource\":[\"arn:aws:es:<ap-south-1>:<220876168477>:domain/chatbot/.kibana-4*\",\"arn:aws:es:<ap-south-1>:<220876168477>:domain/chatbot/messages/_msearch*\",\"arn:aws:es:<ap-south-1>:<220876168477>:domain/chatbot/messages/_search*\"]},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::<220876168477>:root\"},\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:<ap-south-1>:<220876168477>:domain/chatbot/*\"}]}]"}

**Comment by olivierklein** [comment]
We have changed the ES policy to not include public access to Kibana anymore and rather use es-proxy to channel communications to Kibana with AWS IAM headers. Please try with the latest instructions

**Comment by Ta-m** [comment]
and where are those instructions?
